runtime: python39
entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  min_instances: 0      # 0 = escala até zero quando não há tráfego
  max_instances: 2      # limite máximo de instâncias para controlar custo